SQ_SELECT_DOC_ALL = ('select doc.iddocumento'
                          ', doc.nomedoc'
                          ', doc.hash'
                          ', doc.documento'
                          ', gab.idgabarito'
                          ', gabv.idgabaritovalor'
                          ', gabv.idclasse'
                          ', gabv.valor '
                       'from documento doc '
                       'join gabarito gab '
                         'on gab.iddocumento = doc.iddocumento '
                       'join gabaritovalor gabv '
                         'on gabv.idgabarito = gab.idgabarito '
                       'join classevalor cv '
                         'on cv.idclasse = gabv.idclasse '
                   'order by doc.iddocumento'
                          ', doc.hash'
                          ', gab.idgabarito'
                          ', gabv.idgabaritovalor')
